export const COUNTRY_FIND = "FIND_COUNTRY";
export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const GET_ALL = 'GET_ALL';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';